package baristat.Hubway;

/**
 *
 * Enum for .csv column names.
 *
 * @author Tristin Falk
 *
 */
public enum Column {
  TRIP_DURATION,
  STARTTIME,
  STOPTIME,
  START_STATION_ID,
  START_STATION_NAME,
  START_STATION_LATITUDE,
  START_STATION_LONGITUDE,
  END_STATION_ID,
  END_STATION_NAME,
  END_STATION_LATITUDE,
  END_STATION_LONGITUDE,
  BIKEID,
  USERTYPE,
  BIRTH_YEAR,
  GENDER,
}
